### ISSUE TITLE
Question on chapters endpoint, and using public instance as the source for a Beets plugin

### ISSUE THREAD

**Issue by Neurrone** [laxamentumtech/audnexus#215]
Hi,

I'm currently writing a plugin for Beets to help organize audiobooks. I found that Beets really likes to have metadata on chapters of a book for it to do its matching well.

1. I see that the response for the /chapters endpoint has a `isAccurate` field. In what cases would that be false, i.e how reliable is this data? For the few examples that I've tested, this is very accurate.
2. I had to specify a browser user-agent to avoid being blocked when using the audnex.us instance. I'm wondering if it would be OK for me to release the plugin while using that endpoint, or do you prefer that people host their own instances? I notice that the plex agent does use the endpoint but given the user agent blocking, I wanted to check just in case.

**Comment by djdembeck** [comment]
Hey there :wave: 

Love beets!

1. `isAccurate` is an Audible API key that they don't reveal any information about. I just assume it means they have manually synced the chapter times with the data, rather than just using publisher timestamps. But that's a guess.
2. the `api.audnex.us` endpoint is behind Cloudflare and doesn't blacklist any agents at the moment. Likely your agent was listed as a bot and automatically blocked. As for using the public instance, that's up to you. I would recommend making it configurable so that users can easily choose another hosted instance, be it their own or another mirror.

**Comment by Neurrone** [comment]
Thanks.

I've pushed a preliminary version of an [audible plugin for Beets](https://github.com/neurrone/beets-audible). I'd be interested to hear your thoughts if you try it out. I'll make the endpoint configurable soon, currently it is hardcoded to using the public instance.

Beets does have some limitations that prevents it from working well for audiobooks in generally, see the link for details.

**Comment by Neurrone** [comment]
I've found a workaround for said limitations, so I have a beta-quality plugin out.

Its ready for use, see https://github.com/Neurrone/beets-audible

Let me know if the instructions are unclear. I need to create a mod for the linuxserver Beets container to make setting it up with Docker easier.

I've tested this on a variety of books and so far, it has worked on all of them.

Note that the comment tag and text in description.txt is in markdown format.
