### ISSUE TITLE
Ability to search for books without the ASIN

### ISSUE THREAD

**Issue by JaegerMaster** [laxamentumtech/audnexus#687]
Similar to how the API currently allows finding author by author name, it would be great to be able to locate books without needing the ASIN.

Supporting similar functionality to Audible's search page (https://www.audible.com/search) would be a huge plus. That's currently the only way I know of to really find an ASIN. This would allow Audnexus to be used as a main searchable data source rather than having to augment it with external search tools via my own dependency on the audible API.

**Comment by djdembeck** [comment]
While I agree this would be a neat feature, it's a significant burden in a technical sense.

We would have mainly 2 options:
- Use MongoDB text search, which is terrible for real searching (relevance & scoring) and costs DB query time.
- Use an external search system. This would be preferable, but is one more component to add, another docker to run, etc.

Since I'm already close to soft launch of AudiobookDB, I'd rather keep Audnexus as a metadata tool than an all-in-one.
